In [2]:
#import libraries
import pandas as pd
import numpy as np

In [3]:
location = "DC_Properties.csv"
df = pd.read_csv(location)

In [4]:
df.head (10)

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,2,3,1,Hot Water Rad,Y,2,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,3,3,1,Hot Water Rad,Y,2,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,5,3,2,Hot Water Rad,Y,1,10,5,1913.0,NaN,...,-77.039715,Old City 2,040 D Old City 2,4201,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,7,3,1,Hot Water Rad,Y,2,8,4,1906.0,2011.0,...,-77.040129,Old City 2,040 D Old City 2,4201,004201 2005,Ward 2,152,-77.040429,38.914881,NW
5,8,3,1,Warm Cool,Y,2,7,3,1908.0,2008.0,...,-77.039903,Old City 2,040 D Old City 2,4201,004201 2005,Ward 2,152,-77.040429,38.914881,NW
6,14,3,1,Warm Cool,Y,2,5,3,1917.0,2000.0,...,-77.039716,Old City 2,040 D Old City 2,4201,004201 2005,Ward 2,152,-77.040429,38.914881,NW
7,16,3,1,Warm Cool,Y,1,8,3,1908.0,2006.0,...,-77.039844,Old City 2,040 D Old City 2,4201,004201 2005,Ward 2,152,-77.040429,38.914881,NW
8,19,3,1,Hot Water Rad,Y,2,9,3,1908.0,2013.0,...,-77.040138,Old City 2,040 D Old City 2,4201,004201 2005,Ward 2,152,-77.040429,38.914881,NW
9,20,3,1,Hot Water Rad,Y,1,14,5,1880.0,2009.0,...,-77.033774,Old City 2,040 E Old City 2,5201,005201 4003,Ward 2,208,-77.033366,38.911716,NW

In [5]:
df.dtypes

Unnamed: 0              int64
BATHRM                  int64
HF_BATHRM               int64
HEAT                   object
AC                     object
NUM_UNITS               int64
ROOMS                   int64
BEDRM                   int64
AYB                   float64
YR_RMDL               float64
EYB                     int64
STORIES               float64
SALEDATE               object
PRICE                   int64
QUALIFIED              object
SALE_NUM                int64
GBA                     int64
BLDG_NUM                int64
STYLE                  object
STRUCT                 object
GRADE                  object
CNDTN                  object
EXTWALL                object
ROOF                   object
INTWALL                object
KITCHENS              float64
FIREPLACES              int64
USECODE                 int64
LANDAREA                int64
GIS_LAST_MOD_DTTM      object
SOURCE                 object
CMPLX_NUM             float64
LIVING_GBA            float64
FULLADDRESS            object
CITY                   object
STATE                  object
ZIPCODE                 int64
NATIONALGRID           object
LATITUDE              float64
LONGITUDE             float64
ASSESSMENT_NBHD        object
ASSESSMENT_SUBNBHD     object
CENSUS_TRACT            int64
CENSUS_BLOCK           object
WARD                   object
SQUARE                  int64
X                     float64
Y                     float64
QUADRANT               object
dtype: object

In [9]:
np.set_printoptions(suppress=True)

In [10]:
df.corr()

,Unnamed: 0,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,...,LANDAREA,CMPLX_NUM,LIVING_GBA,ZIPCODE,LATITUDE,LONGITUDE,CENSUS_TRACT,SQUARE,X,Y
Unnamed: 0,1.000000,-0.192405,-0.138003,-0.016920,-0.096658,-0.106653,0.407477,0.123567,-0.028442,-0.033282,...,0.053529,NaN,NaN,0.612002,-0.285269,0.593294,0.465704,0.994843,0.593308,-0.285093
BATHRM,-0.192405,1.000000,0.111883,0.383557,0.643709,0.635833,0.091184,0.102598,0.357406,0.028318,...,0.314529,NaN,NaN,-0.060727,0.130475,-0.322846,-0.270970,-0.196980,-0.322829,0.130512
HF_BATHRM,-0.138003,0.111883,1.000000,-0.177096,0.103293,0.134647,0.158692,0.031833,0.355299,0.032563,...,0.153513,NaN,NaN,-0.007135,0.117617,-0.185836,-0.137387,-0.140430,-0.185807,0.118103
NUM_UNITS,-0.016920,0.383557,-0.177096,1.000000,0.537533,0.340592,-0.111540,-0.030131,-0.124943,0.009913,...,-0.056465,NaN,NaN,-0.090539,-0.121733,0.053396,0.078931,-0.014513,0.053415,-0.121900
ROOMS,-0.096658,0.643709,0.103293,0.537533,1.000000,0.686420,0.018613,0.001532,0.126915,0.025780,...,0.293769,NaN,NaN,-0.024830,0.094005,-0.229344,-0.193666,-0.100219,-0.229258,0.093933
BEDRM,-0.106653,0.635833,0.134647,0.340592,0.686420,1.000000,-0.022735,0.039742,0.156578,0.026260,...,0.302540,NaN,NaN,-0.040593,0.166923,-0.259991,-0.238585,-0.112469,-0.259955,0.166875
AYB,0.407477,0.091184,0.158692,-0.111540,0.018613,-0.022735,1.000000,0.083393,0.631409,-0.003989,...,0.138589,NaN,NaN,0.448445,-0.108783,0.173148,0.181268,0.409629,0.173186,-0.107894
YR_RMDL,0.123567,0.102598,0.031833,-0.030131,0.001532,0.039742,0.083393,1.000000,0.195350,-0.003334,...,-0.008118,NaN,NaN,0.049479,0.024887,0.068517,0.038826,0.121016,0.068448,0.024963
EYB,-0.028442,0.357406,0.355299,-0.124943,0.126915,0.156578,0.631409,0.195350,1.000000,0.033932,...,0.099108,NaN,NaN,0.124755,-0.104664,-0.079049,-0.040100,-0.020193,-0.078894,-0.103705
STORIES,-0.033282,0.028318,0.032563,0.009913,0.025780,0.026260,-0.003989,-0.003334,0.033932,1.000000,...,-0.014364,NaN,NaN,-0.019124,-0.004177,-0.023379,-0.017646,-0.032373,-0.023439,-0.004151
PRICE,-0.377618,0.500347,0.260119,-0.000206,0.341814,0.358107,-0.072713,0.053947,0.313203,0.042338,...,0.365841,NaN,NaN,-0.162098,0.159284,-0.437689,-0.369639,-0.381450,-0.437684,0.159353
SALE_NUM,0.023055,0.069772,0.006636,-0.005548,-0.005520,0.009200,-0.027388,0.157701,0.071164,0.009910,...,-0.057398,NaN,NaN,-0.026795,-0.027478,0.051750,0.041370,0.021284,0.051807,-0.027585
GBA,-0.246390,0.696885,0.257129,0.286196,0.680543,0.645797,0.035580,-0.019591,0.285186,0.042298,...,0.495360,NaN,NaN,-0.069938,0.185642,-0.405043,-0.342334,-0.249444,-0.404915,0.185699
BLDG_NUM,-0.015195,-0.009247,-0.013012,-0.001950,-0.017480,-0.023795,-0.006335,-0.003299,-0.002129,-0.000704,...,0.040827,NaN,NaN,-0.007509,-0.002687,-0.011221,-0.012364,-0.014795,-0.011450,-0.002684
KITCHENS,-0.030947,0.401074,-0.154637,0.911616,0.528760,0.353312,-0.118438,-0.013559,-0.102093,0.011535,...,-0.038795,NaN,NaN,-0.098419,-0.103098,0.025906,0.050318,-0.029559,0.025914,-0.103279
FIREPLACES,-0.379524,0.366258,0.250515,-0.041261,0.266683,0.281849,-0.104990,-0.084275,0.181389,0.027976,...,0.332300,NaN,NaN,-0.099222,0.215975,-0.442282,-0.378414,-0.380496,-0.442368,0.216158
USECODE,-0.092356,0.322658,-0.110525,0.804462,0.392763,0.301145,-0.159590,-0.025822,-0.092179,0.011329,...,-0.065222,NaN,NaN,-0.118379,-0.096140,0.030006,0.054049,-0.086899,0.029971,-0.096357
LANDAREA,0.053529,0.314529,0.153513,-0.056465,0.293769,0.302540,0.138589,-0.008118,0.099108,-0.014364,...,1.000000,NaN,NaN,0.206175,0.229064,-0.242253,-0.217959,0.047985,-0.242511,0.228940
CMPLX_NUM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LIVING_GBA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ZIPCODE,0.612002,-0.060727,-0.007135,-0.090539,-0.024830,-0.040593,0.448445,0.049479,0.124755,-0.019124,...,0.206175,NaN,NaN,1.000000,-0.210441,0.183523,0.204226,0.624949,0.183509,-0.210222
LATITUDE,-0.285269,0.130475,0.117617,-0.121733,0.094005,0.166923,-0.108783,0.024887,-0.104664,-0.004177,...,0.229064,NaN,NaN,-0.210441,1.000000,-0.527444,-0.558191,-0.330807,-0.527552,0.999894
LONGITUDE,0.593294,-0.322846,-0.185836,0.053396,-0.229344,-0.259991,0.173148,0.068517,-0.079049,-0.023379,...,-0.242253,NaN,NaN,0.183523,-0.527444,1.000000,0.817179,0.617246,0.999873,-0.527243
CENSUS_TRACT,0.465704,-0.270970,-0.137387,0.078931,-0.193666,-0.238585,0.181268,0.038826,-0.040100,-0.017646,...,-0.217959,NaN,NaN,0.204226,-0.558191,0.817179,1.000000,0.480913,0.817297,-0.558002
SQUARE,0.994843,-0.196980,-0.140430,-0.014513,-0.100219,-0.112469,0.409629,0.121016,-0.020193,-0.032373,...,0.047985,NaN,NaN,0.624949,-0.330807,0.617246,0.480913,1.000000,0.617277,-0.330662
X,0.593308,-0.322829,-0.185807,0.053415,-0.229258,-0.259955,0.173186,0.068448,-0.078894,-0.023439,...,-0.242511,NaN,NaN,0.183509,-0.527552,0.999873,0.817297,0.617277,1.000000,-0.527364
Y,-0.285093,0.130512,0.118103,-0.121900,0.093933,0.166875,-0.107894,0.024963,-0.103705,-0.004151,...,0.228940,NaN,NaN,-0.210222,0.999894,-0.527243,-0.558002,-0.330662,-0.527364,1.000000

In [11]:
import statsmodels.formula.api as smf

In [12]:
result = smf.ols('PRICE ~ LANDAREA', data=df).fit()

In [13]:
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  PRICE   R-squared:                       0.134
Model:                            OLS   Adj. R-squared:                  0.134
Method:                 Least Squares   F-statistic:                     8926.
Date:                Thu, 21 Mar 2019   Prob (F-statistic):               0.00
Time:                        15:25:09   Log-Likelihood:            -8.4718e+05
No. Observations:               57768   AIC:                         1.694e+06
Df Residuals:                   57766   BIC:                         1.694e+06
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   3.562e+05   3343.393    106.534      0.000     3.5e+05    3.63e+05
LANDAREA      70.8174      0.750     94.478      0.000      69.348      72.287
==============================================================================
Omnibus:                    75485.113   Durbin-Watson:                   1.100
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         64363145.551
Skew:                           6.786   Prob(JB):                         0.00
Kurtosis:                     165.960   Cond. No.                     6.33e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 6.33e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""